import { JSDOM } from "jsdom";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  TargetRuntime,
  TARGET_BRIDGE_CHANNEL,
  TARGET_BRIDGE_VERSION,
  isJsonSchema,
  isParentToTargetMessage,
  isTargetToParentMessage,
  type NativeModelContext,
  type ParentToTargetMessage,
  type TargetToolDescriptor,
  type TargetToolRegistration,
} from "../../hosted/targets/target-runtime";
import type { JSONSchema, JsonValue } from "../../core/types";

type NativeRegisteredTool = Parameters<
  NonNullable<NativeModelContext["registerTool"]>
>[0];

interface PostedMessage {
  message: unknown;
  targetOrigin: string;
}

interface RuntimeHarness {
  targetDom: JSDOM;
  parentDom: JSDOM;
  targetWindow: Window;
  parentWindow: Window;
  posts: PostedMessage[];
}

interface NativeHost {
  modelContext: NativeModelContext;
  tools: Map<string, NativeRegisteredTool>;
  registerTool: ReturnType<typeof vi.fn>;
}

const target = {
  id: "commerce",
  name: "Northstar Supply",
  url: "/targets/commerce.html",
};

const objectSchema: JSONSchema = {
  type: "object",
  properties: {},
  required: [],
  additionalProperties: false,
};

const querySchema: JSONSchema = {
  type: "object",
  properties: { query: { type: "string", minLength: 1 } },
  required: ["query"],
  additionalProperties: false,
};

function generatedDescriptor(
  name = "buy_best_product",
  inputSchema: JSONSchema = querySchema,
): TargetToolDescriptor {
  return {
    name,
    description: `${name} generated action.`,
    inputSchema,
    annotations: { destructiveHint: true },
    source: "webmcp",
    confidence: 1,
    evidence: [{ type: "action", note: "Generated by the Studio composer." }],
  };
}

function createHarness(): RuntimeHarness {
  const targetDom = new JSDOM("<main></main>", {
    url: "https://studio.test/targets/commerce.html",
  });
  const parentDom = new JSDOM("<main></main>", {
    url: "https://studio.test/",
  });
  const posts: PostedMessage[] = [];
  const postMessage = vi.fn((message: unknown, targetOrigin: string): void => {
    posts.push({ message, targetOrigin });
  });
  Object.defineProperty(parentDom.window, "postMessage", {
    configurable: true,
    value: postMessage,
  });
  return {
    targetDom,
    parentDom,
    targetWindow: targetDom.window,
    parentWindow: parentDom.window,
    posts,
  };
}

function createNativeHost(): NativeHost {
  const tools = new Map<string, NativeRegisteredTool>();
  const registerTool = vi.fn(
    (tool: NativeRegisteredTool, options?: { signal?: AbortSignal }) => {
      tools.set(tool.name, tool);
      options?.signal?.addEventListener(
        "abort",
        () => tools.delete(tool.name),
        { once: true },
      );
      return Promise.resolve(true);
    },
  );
  const modelContext: NativeModelContext = {
    registerTool,
    unregisterTool: (name) => tools.delete(name),
    getTools: () => Array.from(tools.values()),
  };
  return { modelContext, tools, registerTool };
}

function registration(
  name: string,
  execute: (args: unknown) => JsonValue | Promise<JsonValue> = () => ({
    ok: true,
  }),
  inputSchema: JSONSchema = objectSchema,
): TargetToolRegistration {
  return {
    name,
    description: `${name} target action.`,
    inputSchema,
    annotations: { readOnlyHint: true },
    source: "webmcp",
    confidence: 1,
    evidence: [{ type: "manual", note: "Controlled test target." }],
    execute,
  };
}

function invokeMessage(
  toolName: string,
  args: JsonValue,
  requestId = "request-1",
): ParentToTargetMessage {
  return {
    channel: TARGET_BRIDGE_CHANNEL,
    version: TARGET_BRIDGE_VERSION,
    direction: "parent-to-target",
    type: "invoke-tool",
    requestId,
    toolName,
    args,
  };
}

function registerGeneratedMessage(
  descriptor: TargetToolDescriptor,
  requestId = "generated-register-1",
): ParentToTargetMessage {
  return {
    channel: TARGET_BRIDGE_CHANNEL,
    version: TARGET_BRIDGE_VERSION,
    direction: "parent-to-target",
    type: "register-generated-tool",
    requestId,
    toolName: descriptor.name,
    descriptor,
  };
}

function testGeneratedMessage(
  toolName: string,
  args: JsonValue,
  requestId = "generated-test-1",
): ParentToTargetMessage {
  return {
    channel: TARGET_BRIDGE_CHANNEL,
    version: TARGET_BRIDGE_VERSION,
    direction: "parent-to-target",
    type: "test-generated-tool",
    requestId,
    toolName,
    args,
  };
}

function generatedResultMessage(
  toolName: string,
  requestId: string,
  result: JsonValue,
): ParentToTargetMessage {
  return {
    channel: TARGET_BRIDGE_CHANNEL,
    version: TARGET_BRIDGE_VERSION,
    direction: "parent-to-target",
    type: "generated-tool-result",
    requestId,
    toolName,
    result,
  };
}

function generatedErrorMessage(
  toolName: string,
  requestId: string,
  error: { code: "execution_failed"; message: string },
): ParentToTargetMessage {
  return {
    channel: TARGET_BRIDGE_CHANNEL,
    version: TARGET_BRIDGE_VERSION,
    direction: "parent-to-target",
    type: "generated-tool-error",
    requestId,
    toolName,
    error,
  };
}

function dispatchFromParent(
  harness: RuntimeHarness,
  data: unknown,
  origin = "https://studio.test",
  source: Window = harness.parentWindow,
): void {
  harness.targetWindow.dispatchEvent(
    new MessageEvent("message", {
      data,
      origin,
      source: source as unknown as MessageEventSource,
    }),
  );
}

async function settleMessage(): Promise<void> {
  await Promise.resolve();
  await new Promise<void>((resolve) => setTimeout(resolve, 0));
  await Promise.resolve();
}

function postedOfType(
  harness: RuntimeHarness,
  type: string,
): Record<string, unknown> | undefined {
  const message = harness.posts
    .map(({ message }) => message)
    .find(
      (candidate) =>
        candidate !== null &&
        typeof candidate === "object" &&
        (candidate as { type?: unknown }).type === type,
    );
  return message !== null && typeof message === "object"
    ? (message as Record<string, unknown>)
    : undefined;
}

function postedAllOfType(
  harness: RuntimeHarness,
  type: string,
): Record<string, unknown>[] {
  return harness.posts.flatMap(({ message }) => {
    if (
      message === null ||
      typeof message !== "object" ||
      (message as { type?: unknown }).type !== type
    )
      return [];
    return [message as Record<string, unknown>];
  });
}

const activeHarnesses: RuntimeHarness[] = [];

afterEach(() => {
  for (const harness of activeHarnesses) {
    harness.targetDom.window.close();
    harness.parentDom.window.close();
  }
  activeHarnesses.length = 0;
});

describe("hosted target runtime page injection contract", () => {
  it("accepts valid bridge messages and rejects malformed envelopes", () => {
    const descriptor = {
      name: "search_products",
      description: "Search products.",
      inputSchema: querySchema,
      annotations: { readOnlyHint: true },
      source: "webmcp" as const,
      confidence: 1,
      evidence: [{ type: "manual" as const, note: "Test target." }],
    };
    const ready = {
      channel: TARGET_BRIDGE_CHANNEL,
      version: TARGET_BRIDGE_VERSION,
      direction: "target-to-parent" as const,
      type: "target-ready" as const,
      target,
      mode: "native" as const,
      tools: [descriptor],
    };

    expect(isTargetToParentMessage(ready)).toBe(true);
    expect(
      isTargetToParentMessage({
        ...ready,
        tools: [{ ...descriptor, inputSchema: null }],
      }),
    ).toBe(false);
    expect(
      isTargetToParentMessage({
        ...ready,
        tools: [{ ...descriptor, confidence: 2 }],
      }),
    ).toBe(false);

    const invoke = invokeMessage("search_products", { query: "keyboard" });
    expect(isParentToTargetMessage(invoke)).toBe(true);
    expect(isParentToTargetMessage({ ...invoke, requestId: 7 })).toBe(false);
    expect(
      isParentToTargetMessage({ ...invoke, args: { query: () => "keyboard" } }),
    ).toBe(false);
    expect(
      isParentToTargetMessage({
        channel: TARGET_BRIDGE_CHANNEL,
        version: TARGET_BRIDGE_VERSION,
        direction: "parent-to-target",
        type: "unexpected-command",
      }),
    ).toBe(false);

    const generated = registerGeneratedMessage(generatedDescriptor());
    expect(isParentToTargetMessage(generated)).toBe(true);
    expect(Object.keys(generated).sort()).toEqual([
      "channel",
      "descriptor",
      "direction",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(generated).not.toHaveProperty("generatedName");
    expect(generated).not.toHaveProperty("generatedTool");
    expect(generated).not.toHaveProperty("workflow");
    expect(
      isParentToTargetMessage({
        ...generated,
        descriptor: { ...generatedDescriptor(), description: "Tampered." },
      }),
    ).toBe(true);
    expect(
      isParentToTargetMessage({
        ...generated,
        descriptor: { ...generatedDescriptor("other_tool") },
      }),
    ).toBe(false);
    const missingDescriptor = { ...generated } as Record<string, unknown>;
    delete missingDescriptor.descriptor;
    expect(isParentToTargetMessage(missingDescriptor)).toBe(false);

    const generatedTest = testGeneratedMessage("buy_best_product", {
      query: "keyboard",
    });
    expect(isParentToTargetMessage(generatedTest)).toBe(true);
    expect(Object.keys(generatedTest).sort()).toEqual([
      "args",
      "channel",
      "direction",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(generatedTest).not.toHaveProperty("input");

    const generatedReady = {
      channel: TARGET_BRIDGE_CHANNEL,
      version: TARGET_BRIDGE_VERSION,
      direction: "target-to-parent" as const,
      type: "generated-tool-ready" as const,
      requestId: "generated-register-1",
      toolName: "buy_best_product",
      registered: true,
      mode: "native" as const,
    };
    expect(isTargetToParentMessage(generatedReady)).toBe(true);
    expect(Object.keys(generatedReady).sort()).toEqual([
      "channel",
      "direction",
      "mode",
      "registered",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(generatedReady).not.toHaveProperty("generatedName");
    expect(generatedReady).not.toHaveProperty("status");
  });

  it("supports provideTool hosts, string schemas, and native executeTool tests", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const tools = new Map<string, NativeRegisteredTool>();
    const provideTool = vi.fn((tool: NativeRegisteredTool): boolean => {
      if (typeof tool.inputSchema !== "string") return false;
      tools.set(tool.name, tool);
      return true;
    });
    const executeTool = vi.fn(async (tool: unknown, input: unknown) => {
      if (!tool || typeof tool !== "object") throw new Error("Missing tool.");
      const registered = tools.get((tool as { name: string }).name);
      if (!registered?.execute) throw new Error("Tool is not registered.");
      if (typeof input !== "string") throw new Error("String input required.");
      return registered.execute(JSON.parse(input));
    });
    const host: NativeModelContext = {
      provideTool,
      getTools: () => Array.from(tools.values()),
      executeTool,
    };
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: host,
    });
    runtime.addTool(registration("search_products", undefined, querySchema));
    await runtime.start();

    expect(runtime.mode).toBe("native");
    expect(provideTool).toHaveBeenCalledTimes(2);
    expect(typeof provideTool.mock.calls[1]?.[0].inputSchema).toBe("string");
    expect(
      isJsonSchema(
        JSON.parse(provideTool.mock.calls[1]![0].inputSchema as string),
      ),
    ).toBe(true);

    const descriptor = generatedDescriptor();
    await expect(
      runtime.registerGeneratedTool(descriptor),
    ).resolves.toMatchObject({
      registered: true,
      mode: "native",
    });
    const invocation = runtime.testGeneratedTool(
      descriptor.name,
      { query: "keyboard" },
      "native-test-1",
    );
    await settleMessage();
    const call = postedOfType(harness, "generated-tool-call");
    if (typeof call?.requestId !== "string")
      throw new Error("Native test did not reach the generated handler.");
    dispatchFromParent(
      harness,
      generatedResultMessage(descriptor.name, call.requestId, {
        success: true,
        stateChanged: true,
      }),
    );
    await expect(invocation).resolves.toMatchObject({
      success: true,
      stateChanged: true,
    });
    expect(executeTool).toHaveBeenCalledWith(
      expect.objectContaining({ name: descriptor.name }),
      JSON.stringify({ query: "keyboard" }),
    );
  });

  it("does not claim or remove a pre-existing native tool", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const host = createNativeHost();
    const existing: NativeRegisteredTool = {
      name: "search_products",
      description: "Owned by the host before Studio loaded.",
      inputSchema: objectSchema,
      annotations: {},
      execute: () => ({ owner: "host" }),
    };
    host.tools.set(existing.name, existing);

    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: host.modelContext,
    });
    runtime.addTool(registration("search_products"));
    await runtime.start();

    expect(host.registerTool).not.toHaveBeenCalled();
    expect(host.tools.get(existing.name)).toBe(existing);
    runtime.stop();
    expect(host.tools.get(existing.name)).toBe(existing);
  });

  it("does not publish a delayed registration after the runtime stops", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const tools = new Map<string, NativeRegisteredTool>();
    let release: ((value: boolean) => void) | undefined;
    const registerTool = vi.fn(
      (tool: NativeRegisteredTool, options?: { signal?: AbortSignal }) => {
        tools.set(tool.name, tool);
        options?.signal?.addEventListener(
          "abort",
          () => tools.delete(tool.name),
          { once: true },
        );
        return new Promise<boolean>((resolve) => {
          release = resolve;
        });
      },
    );
    const host: NativeModelContext = {
      registerTool,
      unregisterTool: (name) => tools.delete(name),
      getTools: () => Array.from(tools.values()),
    };
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: host,
    });
    runtime.addTool(registration("search_products"));

    const started = runtime.start();
    await settleMessage();
    expect(registerTool).toHaveBeenCalledTimes(1);
    runtime.stop();
    release?.(true);
    await started;

    expect(tools.has("search_products")).toBe(false);
    expect(postedOfType(harness, "target-ready")).toBeUndefined();
    await expect(runtime.invoke("search_products", {})).rejects.toMatchObject({
      code: "runtime_stopped",
    });
  });

  it("rejects duplicate target registrations and reports unknown tools", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: null,
    });
    runtime.addTool(registration("search_products"));

    expect(() => runtime.addTool(registration(" search_products "))).toThrow(
      "already registered",
    );
    await expect(runtime.invoke("missing_tool", {})).rejects.toMatchObject({
      code: "unknown_tool",
    });

    await runtime.start();
    harness.posts.length = 0;
    dispatchFromParent(harness, invokeMessage("missing_tool", {}));
    await settleMessage();

    const error = postedOfType(harness, "tool-error");
    expect(error).toMatchObject({
      requestId: "request-1",
      toolName: "missing_tool",
      error: {
        code: "unknown_tool",
      },
    });
  });

  it("ignores malformed, cross-origin, and cross-window messages", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const otherWindow = new JSDOM("<main></main>", {
      url: "https://studio.test/other",
    }).window;
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: null,
    });
    runtime.addTool(registration("known_tool"));
    await runtime.start();
    harness.posts.length = 0;

    const valid = invokeMessage("known_tool", {});
    dispatchFromParent(harness, { ...valid, args: { bad: () => true } });
    dispatchFromParent(harness, valid, "https://evil.test");
    dispatchFromParent(harness, valid, "https://studio.test", otherWindow);
    await settleMessage();

    expect(harness.posts).toEqual([]);
    otherWindow.close();
  });

  it("round-trips a generated handler through native registration and the parent bridge", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const host = createNativeHost();
    const calls: string[] = [];
    let runtime!: TargetRuntime;
    const generated = registration(
      "buy_best_product",
      async (args) => {
        const input = args as { productId: string; query: string };
        const search = await runtime.invoke("search_products", {
          query: input.query,
        });
        const cart = await runtime.invoke("add_to_cart", {
          productId: input.productId,
        });
        return { ok: true, search, cart };
      },
      {
        type: "object",
        properties: {
          query: { type: "string", minLength: 1 },
          productId: { type: "string", minLength: 1 },
        },
        required: ["query", "productId"],
        additionalProperties: false,
      },
    );
    runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: host.modelContext,
    });
    runtime
      .addTool(
        registration(
          "search_products",
          (args) => {
            calls.push(`search:${String((args as { query: string }).query)}`);
            return { productId: "keyboard-1" };
          },
          querySchema,
        ),
      )
      .addTool(
        registration(
          "add_to_cart",
          (args) => {
            calls.push(
              `cart:${String((args as { productId: string }).productId)}`,
            );
            return { cartCount: 1, stateChanged: true };
          },
          {
            type: "object",
            properties: { productId: { type: "string", minLength: 1 } },
            required: ["productId"],
            additionalProperties: false,
          },
        ) as TargetToolRegistration,
      )
      .addTool(generated);

    await runtime.start();

    expect(runtime.mode).toBe("native");
    expect(host.tools.has("buy_best_product")).toBe(true);
    const nativeTool = host.tools.get("buy_best_product");
    if (!nativeTool?.execute) throw new Error("Generated tool was not native.");
    expect(nativeTool).not.toHaveProperty("source");
    expect(nativeTool).not.toHaveProperty("evidence");
    expect(nativeTool).not.toHaveProperty("confidence");
    await expect(
      nativeTool.execute({ query: "keyboard", productId: "keyboard-1" }),
    ).resolves.toMatchObject({ ok: true, cart: { cartCount: 1 } });
    expect(calls).toEqual(["search:keyboard", "cart:keyboard-1"]);

    calls.length = 0;
    harness.posts.length = 0;
    dispatchFromParent(
      harness,
      invokeMessage(
        "buy_best_product",
        { query: "keyboard", productId: "keyboard-1" },
        "generated-request",
      ),
    );
    await settleMessage();

    const result = postedOfType(harness, "tool-result");
    expect(result).toMatchObject({
      requestId: "generated-request",
      toolName: "buy_best_product",
      result: { ok: true, cart: { cartCount: 1, stateChanged: true } },
    });
    expect(calls).toEqual(["search:keyboard", "cart:keyboard-1"]);

    runtime.stop();
    expect(host.tools.size).toBe(0);
  });

  it("registers the Studio publication envelope and correlates native calls", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const host = createNativeHost();
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: host.modelContext,
    });
    runtime.addTool(registration("search_products", undefined, querySchema));
    await runtime.start();
    harness.posts.length = 0;

    const descriptor = generatedDescriptor();
    dispatchFromParent(harness, registerGeneratedMessage(descriptor));
    await settleMessage();

    const ready = postedOfType(harness, "generated-tool-ready");
    expect(ready).toMatchObject({
      requestId: "generated-register-1",
      toolName: descriptor.name,
      registered: true,
      mode: "native",
    });
    expect(Object.keys(ready ?? {}).sort()).toEqual([
      "channel",
      "direction",
      "mode",
      "registered",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(ready).not.toHaveProperty("generatedName");
    expect(ready).not.toHaveProperty("status");
    expect(isTargetToParentMessage(ready)).toBe(true);
    expect(runtime.getGeneratedToolDescriptors()).toEqual([descriptor]);
    expect(runtime.getToolDescriptors().map(({ name }) => name)).toEqual([
      "search_products",
      descriptor.name,
    ]);

    const nativeTool = host.tools.get(descriptor.name);
    if (!nativeTool?.execute)
      throw new Error("Generated tool was not registered natively.");
    const invocation = nativeTool.execute({ query: "keyboard" });
    await settleMessage();

    const call = postedOfType(harness, "generated-tool-call");
    expect(call).toMatchObject({
      toolName: descriptor.name,
      args: { query: "keyboard" },
    });
    expect(Object.keys(call ?? {}).sort()).toEqual([
      "args",
      "channel",
      "direction",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(call).not.toHaveProperty("generatedName");
    if (typeof call?.requestId !== "string")
      throw new Error("Generated invocation did not include a request ID.");

    dispatchFromParent(
      harness,
      generatedResultMessage(descriptor.name, call.requestId, {
        success: true,
        stateChanged: true,
      }),
    );
    await expect(invocation).resolves.toEqual({
      success: true,
      stateChanged: true,
    });

    const mismatchedInvocation = nativeTool.execute({ query: "mouse" });
    await settleMessage();
    const calls = postedAllOfType(harness, "generated-tool-call");
    const mismatchedCall = calls.at(-1);
    if (typeof mismatchedCall?.requestId !== "string")
      throw new Error("Second generated invocation did not include an ID.");
    dispatchFromParent(
      harness,
      generatedResultMessage("other_generated_tool", mismatchedCall.requestId, {
        success: true,
      }),
    );
    await expect(mismatchedInvocation).rejects.toMatchObject({
      code: "invalid_message",
    });

    const mismatchedErrorInvocation = nativeTool.execute({ query: "monitor" });
    await settleMessage();
    const errorCall = postedAllOfType(harness, "generated-tool-call").at(-1);
    if (typeof errorCall?.requestId !== "string")
      throw new Error("Generated error invocation did not include an ID.");
    dispatchFromParent(
      harness,
      generatedErrorMessage("other_generated_tool", errorCall.requestId, {
        code: "execution_failed",
        message: "Wrong tool response.",
      }),
    );
    await expect(mismatchedErrorInvocation).rejects.toMatchObject({
      code: "invalid_message",
    });
  });

  it("round-trips a page-level test through the preview bridge", async () => {
    const harness = createHarness();
    activeHarnesses.push(harness);
    const runtime = new TargetRuntime({
      target,
      document: harness.targetDom.window.document,
      pageWindow: harness.targetWindow,
      parentWindow: harness.parentWindow,
      modelContext: null,
    });
    runtime.addTool(registration("search_products", undefined, querySchema));
    await runtime.start();
    harness.posts.length = 0;

    const descriptor = generatedDescriptor();
    dispatchFromParent(harness, registerGeneratedMessage(descriptor));
    await settleMessage();
    expect(postedOfType(harness, "generated-tool-ready")).toMatchObject({
      requestId: "generated-register-1",
      toolName: descriptor.name,
      registered: true,
      mode: "preview",
      error: { code: "webmcp_unavailable" },
    });
    const ready = postedOfType(harness, "generated-tool-ready");
    expect(Object.keys(ready ?? {}).sort()).toEqual([
      "channel",
      "direction",
      "error",
      "mode",
      "registered",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(ready).not.toHaveProperty("generatedName");
    expect(ready).not.toHaveProperty("status");

    const testRequestId = "generated-test-1";
    dispatchFromParent(
      harness,
      testGeneratedMessage(
        descriptor.name,
        { query: "keyboard" },
        testRequestId,
      ),
    );
    await settleMessage();
    const call = postedAllOfType(harness, "generated-tool-call").at(-1);
    expect(call).toMatchObject({
      requestId: testRequestId,
      toolName: descriptor.name,
    });
    expect(Object.keys(call ?? {}).sort()).toEqual([
      "args",
      "channel",
      "direction",
      "requestId",
      "toolName",
      "type",
      "version",
    ]);
    expect(call).not.toHaveProperty("generatedName");

    // A replayed test request cannot steal or replace the first pending call.
    dispatchFromParent(
      harness,
      testGeneratedMessage(
        descriptor.name,
        { query: "keyboard" },
        testRequestId,
      ),
    );
    await settleMessage();
    expect(
      postedAllOfType(harness, "generated-tool-test-error").at(-1),
    ).toMatchObject({
      requestId: testRequestId,
      toolName: descriptor.name,
      error: { code: "duplicate_request" },
    });

    dispatchFromParent(
      harness,
      generatedResultMessage(descriptor.name, testRequestId, {
        success: true,
        stateChanged: true,
      }),
    );
    await settleMessage();
    expect(
      postedAllOfType(harness, "generated-tool-test-result").at(-1),
    ).toMatchObject({
      requestId: testRequestId,
      toolName: descriptor.name,
      result: { success: true, stateChanged: true },
    });
    const testResult = postedAllOfType(
      harness,
      "generated-tool-test-result",
    ).at(-1);
    expect(Object.keys(testResult ?? {}).sort()).toEqual([
      "channel",
      "direction",
      "requestId",
      "result",
      "toolName",
      "type",
      "version",
    ]);
    expect(testResult).not.toHaveProperty("generatedName");
  });
});
